{% set SLICEDIMAGE_VERSION = "4.1.1" %}

package:
  name: slicedimage
  version: {{ SLICEDIMAGE_VERSION }}

source:
  url:  https://github.com/spacetx/slicedimage/archive/{{ SLICEDIMAGE_VERSION }}.zip
  sha256: 1cf6a685f7e0af249febd52972bdaf6dc58fdc408a7c45c48912200522a58690

build:
  noarch: python
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
  run:
    - boto3
    - python >={{ python_min }}
    - numpy
    - diskcache
    - packaging
    - requests
    - imageio

test:
  requires:
    - python {{ python_min }}
  imports:
    - slicedimage

about:
  home: https://github.com/spacetx/slicedimage
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python module to access sliced imaging data

extra:
  recipe-maintainers:
    - micknudsen
