{% set SLICEDIMAGE_VERSION = "4.0.4" %}

package:
  name: slicedimage
  version: {{ SLICEDIMAGE_VERSION }}

source:
  url:  https://github.com/spacetx/slicedimage/archive/{{ SLICEDIMAGE_VERSION }}.zip
  sha256: a32c736a6cc5d5c99fd2d75dab8d64208ea488259570c9a76bb515f758a2fc2d

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - boto3
    - python >=3.6
    - numpy
    - diskcache
    - packaging
    - requests
    - scikit-image
    - tifffile

test:
  imports:
    - slicedimage

about:
  home: https://github.com/spacetx/slicedimage
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python module to access sliced imaging data

extra:
  recipe-maintainers:
    - micknudsen
