{% set SLICEDIMAGE_VERSION = "4.0.4" %}

package:
  name: slicedimage
  version: {{ SLICEDIMAGE_VERSION }}

source:
  url:  https://github.com/spacetx/slicedimage/archive/{{ SLICEDIMAGE_VERSION }}.zip
  sha256: 50a138a769f4a08e18ccc56586e9dfe5689551b8fd4afff828bc9b07af519727

build:
  noarch: python
  number: 0

requirements:
  build:
    - python >=3.6
    - setuptools
  run:
    - boto3
    - python >=3.6
    - numpy
    - diskcache
    - packaging
    - requests
    - scikit-image
    - tifffile

test:
  imports:
    - slicedimage

about:
  home: https://github.com/spacetx/slicedimage
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Python module to access sliced imaging data

extra:
  recipe-maintainers:
    - micknudsen
