travis:
  secure:
    BINSTAR_TOKEN: b3mMeNZtxqfWxgdJVb2JjqNAwqSRs+vA5ZhdMQFHI9SeXjCwrUfqjok8dfl/+EB7/cr1xoj+08YQT2vawvDEVvKmBS699KbQ5Vxbasw1fjUgyNchH0tZTVyS/CiDSjyNmwmIXQkAun+k+af5DBbRrM0O+8SBWEe/Opb0Yj+rLvF9RtcLArlL/pHK0VG7rgnkFEjVsTcUzhifLxUHsBRCdkKGLc6evqO+uJh/QKCXO6qKJEN6oxirYmfPSOroze68qmsB2b41tO0ezSCF2KlMhShEqbSYQqRGOqxzEBAJEt8ALaiVKlCgnoClMszz8ls19S/Vr/I5C+FPGAm08bufGDLo2t01MP9+XKNHDJ+0y/bzVsXdXviTnSAd6B92b5T+fyBVVhbk1Bc9VPvurutEBdWh55obbIVvYyeVCvjLoqp56MbUikGyJX538ifSxySbgrqbxjaghLg6l3oie9dqBTi3djBzjE9deyatywAebpBFVmp38dGX+XkJr3MBGAORtDIEY1sokGnDoy38d+vIDFX+biAOc0Ccya73rwFui9gHb1qYxxglRe7V0sso1cuCtJ2FW79/RFEIcESmkEnWmqoIeqvOw0mpL0cR/Ip8AHRn+eoiLdQdmrqEKvqSYYfNUJHLIa1rTDeccs97h4NxOVFohg/e4GNrVW6Pqx0OEgQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
